version: "3.8"

networks:
  custom:
    name: custom


services:

  # nginx service
  web:
    container_name: "web"
    image: nginx:alpine
    restart: unless-stopped
    depends_on:
      - certbot
    ports:
      - "8082:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./certbot:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: '/bin/sh -c "while :; do sleep 24h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'
    networks:
      - custom

  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: unless-stopped
    depends_on:
      - app
    volumes:
      - ./certbot:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 744h & wait $${!}; done;'"
    networks:
      - custom

  # application service
  app:
    container_name: "app"
    image: app
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8000:8000"
    networks:
      - custom
