version: "3.8"
services:

  # nginx service
  web:
    container_name: "web"
    image: nginx:alpine
    depends_on:
      - app
    ports:
      - "8082:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - custom
    restart: always

  # application service
  app:
    container_name: "my_project_app"
    image: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    networks:
      - custom
